version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
  web:
    build: ./
    environment:
      DBHOST: mysql
      MYSQL_PORT: 3306
      DBNAME: testdb
      DBUSER: root
      DBPASSWORD: password
      DBFOLDER: ./database/
      # Set port for the API service
      PORT: 3000
      # Set the secret key to be used by JSON Web Token Authentication
      SECRETKEY: secret
      # Set logging status 
      CONSOLELOG: 'false'
      LOGFILE: 'true'
      # Initial admin properties
      ADMINNAME: admin
      ADMINPASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "start-docker"]
    restart: on-failure 